### ISSUE TITLE
Error Call to a member function getShippingMethodTypeName() on null

### ISSUE THREAD

**Issue by baxterdmutt** [concretecms-community-store/community_store_easypost#10]
I'm getting this error on an upgraded 9.2.2 version of Concrete running php 8 

/usr/local/share/concrete5/concrete-cms-9.2.2/packages/community_store/single_pages/dashboard/store/settings/shipping.php127

**Comment by Mesuva** [comment]
This seems to be similar to #823, in that it's triggered by uninstalling add-ons, but Community Store still is referencing them.

If you look at the database table CommunityStoreShippingMethods, do you see shipping methods listed there that you know you currently don't have installed?

**Comment by baxterdmutt** [comment]
I had already checked the database table CommunityStoreShippingMethods but did not check  CommunityStoreShippingMethodsTypes.   Easy post was in it twice. The upgrade to 9.2.2 destroyed Community store on both servers that I use it on. I have no idea why. I’ve had to manually uninstall and reinstall community store on both. 
As always, thanks for your fast reply.
