### ISSUE TITLE
Handling after order

### ISSUE THREAD

**Issue by Jozzeh** [concretecms-community-store/community_store_easypost#2]
Hi, 

This add-on looks great to ship packages to a lot of countries from community store.   
A lot of carriers are supported thus a lot of countries as well...  

Few questions : 
1. Is it easy to start a contract through easypost with a carrier?   
2. After an order has been made, a shipment/label and tracking has been generated... How does the owner of the e-shop sends its package? Does the carrier pick up the package at the senders address, or does the owner need to deliver the package to a central pickup-point?   
3. In the video you request a refund... So requesting a refund is cancelling the shipment?   

I think these are questions a shop owner are likely to ask.

**Comment by Mesuva** [comment]
1. - I'm not sure!  I've only used the developer/testing account at this point. But I think it depends on the individual carriers.

2. - I think this comes down to the specific carrier being used. EasyPost is only the aggregator of the online services that allow you to pay for shipping and print the labels, not really anything to do with the actual dispatchment.

3. - Yes, it's cancelling it. You can only do that in certain circumstances, i.e. before anything has been collected.

**Comment by Jozzeh** [comment]
Thanks, I'll close the issue, and comment in the future if I know some more details about the dispatching.
