### ISSUE TITLE
1.x | Shipping options don't load

### ISSUE THREAD

**Issue by FortyNinjaFISH** [concretecms-community-store/community_store_easypost#3]
Getting the following error when trying to checkout. All fields are set for EasyPost Settings and Shipping Methods.

`{"error":{"message":"Fatal error: Call to undefined method Concrete\\Package\\CommunityStore\\Src\\CommunityStore\\Product\\Product::isSeperateShip()"},"errors":["Fatal error: Call to undefined method Concrete\\Package\\CommunityStore\\Src\\CommunityStore\\Product\\Product::isSeperateShip()"]}`

Easypost Shipping 1.x (v0.9.9)
Community Store 1.x (v1.3.4)
Concrete5 7.5.13 running PHP7.0

https://www.jigsawlearning.ca/store/products/envisioning-collaborative-response-model-book/

![Jigsaw Learning - Checkout](https://user-images.githubusercontent.com/20685707/59884830-a975bb80-9376-11e9-8cbe-086bec259a0f.png)

![Jigsaw Learning - EasyPost Settings](https://user-images.githubusercontent.com/20685707/59884832-aa0e5200-9376-11e9-9c57-3d491819b758.png)

![Jigsaw Learning - Product Settings](https://user-images.githubusercontent.com/20685707/59884833-aa0e5200-9376-11e9-9713-aa1ca284a421.png)

![Jigsaw Learning - Shipping Method](https://user-images.githubusercontent.com/20685707/59884834-aa0e5200-9376-11e9-8772-671f61081498.png)

**Comment by FortyNinjaFISH** [comment]
Anyone able to assist?

**Comment by Mesuva** [comment]
Sorry, I thought I'd commented on this earlier, but my message mustn't have saved.

The issue here is that your Community Store version is a bit old, and missing the function isSeperateShip, which was added around 1.4.7 I think.

You may need to either upgrade your CS version

**Comment by FortyNinjaFISH** [comment]
Will try and update to 1.4.7- Thanks Mesuva.

**Comment by FortyNinjaFISH** [comment]
Thanks again Mesuva. It appears the "isSeperateShip" function is included in CS1.4.2. I tried 1.4.7 but the store checkout hangs when entering shipping/billing address information. Sticking with 1.4.2 for now.
