### ISSUE TITLE
Service Restrictions

### ISSUE THREAD

**Issue by FortyNinjaFISH** [concretecms-community-store/community_store_easypost#4]
When entering preferred service restrictions into EasyPost Shipping Methods on the last option in the list appears. I have the following:

Carrier Restriction: 
- CanadaPost

Service Restriction:
- XpressPost
- RegularParcel

Only RegularParcel appears during checkout. Both options entered plus two others appear if i leave the Service Restrictions box blank. It would be preferrable to display the enter options (if they are available of course - in this case they both are).

Service Restriction left blank:
![Empty](https://user-images.githubusercontent.com/20685707/60052216-ea7d1100-9691-11e9-8bd8-291d7368ebe0.jpg)

Service Restriction populated:
![Populated](https://user-images.githubusercontent.com/20685707/60052219-ec46d480-9691-11e9-821d-b1918290b89c.jpg)

**Comment by Mesuva** [comment]
Thanks for the detail here - I've tracked this down and you can manually apply this fix here:
https://github.com/concrete5-community-store/community_store_easypost/commit/15a3037dbc32e6b6227dae2b87b26d076e1084f9

**Comment by FortyNinjaFISH** [comment]
Thanks again Mesuva. 
The manual updates applied to 'EasypostShippingMethod.php' appear to have worked for me in version 1.x
