### ISSUE TITLE
Trying to add a new EasyPost Shipping Method

### ISSUE THREAD

**Issue by mdius** [concretecms-community-store/community_store_easypost#7]
I am trying to add a new method mirroring the current EasyPost Shipping - UPS, but "EasyPost Shipping - USPS" instead. I want to add like a 20% increase to the USPS shipping price, but not UPS. I get an error when trying to add.
`An exception occurred while executing 'INSERT INTO CommunityStoreEasypostMethods (company, street1, street2, city, state, country, zip, phone, countriesSelected, fallbackWeight, fallbackWidth, fallbackLength, fallbackHeight, noMatch, noMatchLabel, noMatchDetails, noMatchRate, carrierFilter, serviceFilter, adjustmentFactor, rateType, smID, disableEnabled) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["MDI Inc.", "25028 US Highway 12 East", "", "Edwardsburg", "MI", "United States", "49112", "(269) 663-8574", "CA,MX,US", 75, 50, 50, 50, "0", "", "", "", "USPS", "", "20", "rate", null, null]: SQLSTATE[01000]: Warning: 1265 Data truncated for column 'noMatchRate' at row 1`

I know you can log in to the site, if you want to have a look you may, or I can try to supply more details.

**Comment by Mesuva** [comment]
I've tracked this one down - it was just issues when in MySQL strict mode.
I've pushed updates to github, as well as apply these fixes directly to your site - let me know if if you hit other issues.
